Excercise1
1) Create Two numpy array of size 4 X 5 and 5 X 4.
2) Randomly Initalize that array
3) Perform matrix multiplication

In [ ]:
import numpy as np

# Create two 4x4 arrays
A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16]])

B = np.array([[4, 3, 2, 1],
              [8, 7, 6, 5],
              [12, 11, 10, 9],
              [16, 15, 14, 13]])

# Define functions to calculate determinant, transpose, norm, and matrix multiplication
def determinant(matrix):
    """Calculate the determinant of a matrix"""
    return np.linalg.det(matrix)

def transpose(matrix):
    """Calculate the transpose of a matrix"""
    return matrix.T

def norm(matrix):
    """Calculate the norm of a matrix"""
    return np.linalg.norm(matrix)

def matrix_multiplication(matrix1, matrix2):
    """Perform matrix multiplication of two matrices"""
    return np.matmul(matrix1, matrix2)

# Calculate the determinant of A and B
detA = determinant(A)
detB = determinant(B)
print("Determinant of matrix A: ", detA)
print("Determinant of matrix B: ", detB)

# Calculate the transpose of A and B
AT = transpose(A)
BT = transpose(B)
print("Transpose of matrix A: \n", AT)
print("Transpose of matrix B: \n", BT)

# Calculate the norm of A and B
normA = norm(A)
normB = norm(B)
print("Norm of matrix A: ", normA)
print("Norm of matrix B: ", normB)

# Perform matrix multiplication of A and B
C = matrix_multiplication(A, B)
print("Result of matrix multiplication of A and B: \n", C)

Determinant of matrix A:  0.0
Determinant of matrix B:  0.0
Transpose of matrix A: 
 [[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]
Transpose of matrix B: 
 [[ 4  8 12 16]
 [ 3  7 11 15]
 [ 2  6 10 14]
 [ 1  5  9 13]]
Norm of matrix A:  38.67815921162743
Norm of matrix B:  38.67815921162743
Result of matrix multiplication of A and B: 
 [[120 110 100  90]
 [280 254 228 202]
 [440 398 356 314]
 [600 542 484 426]]


In [ ]:
tweet = "Just watched an amazing movie with my friends"
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('wordnet')

stop_words = set(stopwords.words('english'))

tokens = word_tokenize(tweet.lower())

tokens = [token for token in tokens if token.isalnum() and token not in stop_words]
from nltk.stem import PorterStemmer, WordNetLemmatizer

porter = PorterStemmer()
wordnet_lemmatizer = WordNetLemmatizer()

stemmed_tokens = [porter.stem(token) for token in tokens]
lemmatized_tokens = [wordnet_lemmatizer.lemmatize(token) for token in tokens]
# Stemmed Tokens: ['watch', 'amaz', 'movi', 'friend', 'love', 'spend', 'time', 'movienight', 'friend', 'fun']
# Lemmatized Tokens: ['watched', 'amazing', 'movie', 'friend', 'love', 'spending', 'time', 'movienight', 'friend', 'fun']

