In [ ]:
import pandas as pd
import numpy as np
import io
from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.naive_bayes import GaussianNB,MultinomialNB

In [ ]:
datasets = pd.read_csv("Dataset2.csv")

In [ ]:
datasets

Outlook Temp Wind Humidity Class
0        R    H    F   Normal     N
1        R    H    T     High     N
2        O    H    F   Normal     Y
3        S    M    F   Normal     N
4        S    M    F   Normal     Y
5        S    M    T      Low     Y
6        O    C    T   Normal     Y
7        R    C    F   Normal     Y
8        R    C    F      Low     Y
9        S    M    F     High     Y
10       R    M    T     High     Y
11       O    M    T      Low     Y
12       O    H    F   Normal     Y
13       S    M    T   Normal     N

In [ ]:
le = LabelEncoder()
X=datasets.iloc[:,:-1].values
Y=datasets.iloc[:,-1].values
outlook_encoded=le.fit_transform(X[:,0])
outlook_encoded

array([1, 1, 0, 2, 2, 2, 0, 1, 1, 2, 1, 0, 0, 2])

In [ ]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(target_test, target_pred))

Accuracy: 0.8457869634340223


In [ ]:
temp_encoded=le.fit_transform(X[:,1])
temp_encoded

array([1, 1, 1, 2, 2, 2, 0, 0, 0, 2, 2, 2, 1, 2])

In [ ]:
Wind_encoded=le.fit_transform(X[:,2])
Wind_encoded

array([0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1])

In [ ]:
humidity_encoded=le.fit_transform(X[:,3])
humidity_encoded

array([2, 0, 2, 2, 2, 1, 2, 2, 1, 0, 0, 1, 2, 2])

In [ ]:
Y

array(['N', 'N', 'Y', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y',
       'N'], dtype=object)

In [ ]:
features= np.array(list(zip(outlook_encoded,temp_encoded,Wind_encoded,humidity_encoded)),dtype=object)

print("Features: ", features)
print("Target: ",Y)
from sklearn.model_selection import train_test_split
data_train, data_test, target_train, target_test = train_test_split(features,
Y, test_size = 0.1, random_state = 51)
print(data_train.shape,target_train.shape)

Features:  [[1 1 0 2]
 [1 1 1 0]
 [0 1 0 2]
 [2 2 0 2]
 [2 2 0 2]
 [2 2 1 1]
 [0 0 1 2]
 [1 0 0 2]
 [1 0 0 1]
 [2 2 0 0]
 [1 2 1 0]
 [0 2 1 1]
 [0 1 0 2]
 [2 2 1 2]]
Target:  ['N' 'N' 'Y' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N']
(12, 4) (12,)


In [ ]:
data_test

array([[2, 2, 0, 2],
       [1, 0, 0, 1]], dtype=object)

In [ ]:
import numpy as np
gnb = GaussianNB()
gnb.fit(data_train, target_train)
target_pred = gnb.predict(data_test)
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(target_test, target_pred))

Accuracy: 0.5


In [ ]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
precision = precision_score(target_test, target_pred, average=None)
recall = recall_score(target_test, target_pred, average=None)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

precision: [0.  0.5]
recall: [0. 1.]


/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
pre=[1,2,2,0]
np.array(pre).reshape(1,-1)

array([[1, 2, 2, 0]])

In [ ]:
gnb.predict(np.array(pre).reshape(1,-1))


array(['N'], dtype='<U1')

In [ ]:
gnb.predict_proba(np.array(pre).reshape(1,-1))

array([[0.57508912, 0.42491088]])

In [ ]:
pre=[2,0,0,1]
np.array(pre).reshape(1,-1)



array([[2, 0, 0, 1]])

In [ ]:
gnb.predict(np.array(pre).reshape(1,-1))

array(['Y'], dtype='<U1')

In [ ]:
gnb.predict_proba(np.array(pre).reshape(1,-1))

array([[0.03042871, 0.96957129]])

# Task-2

In [ ]:
import sklearn
from sklearn import datasets
digit_data = sklearn.datasets.load_digits();
features = digit_data.feature_names
targets = digit_data.target_names
print(digit_data.feature_names)

['pixel_0_0', 'pixel_0_1', 'pixel_0_2', 'pixel_0_3', 'pixel_0_4', 'pixel_0_5', 'pixel_0_6', 'pixel_0_7', 'pixel_1_0', 'pixel_1_1', 'pixel_1_2', 'pixel_1_3', 'pixel_1_4', 'pixel_1_5', 'pixel_1_6', 'pixel_1_7', 'pixel_2_0', 'pixel_2_1', 'pixel_2_2', 'pixel_2_3', 'pixel_2_4', 'pixel_2_5', 'pixel_2_6', 'pixel_2_7', 'pixel_3_0', 'pixel_3_1', 'pixel_3_2', 'pixel_3_3', 'pixel_3_4', 'pixel_3_5', 'pixel_3_6', 'pixel_3_7', 'pixel_4_0', 'pixel_4_1', 'pixel_4_2', 'pixel_4_3', 'pixel_4_4', 'pixel_4_5', 'pixel_4_6', 'pixel_4_7', 'pixel_5_0', 'pixel_5_1', 'pixel_5_2', 'pixel_5_3', 'pixel_5_4', 'pixel_5_5', 'pixel_5_6', 'pixel_5_7', 'pixel_6_0', 'pixel_6_1', 'pixel_6_2', 'pixel_6_3', 'pixel_6_4', 'pixel_6_5', 'pixel_6_6', 'pixel_6_7', 'pixel_7_0', 'pixel_7_1', 'pixel_7_2', 'pixel_7_3', 'pixel_7_4', 'pixel_7_5', 'pixel_7_6', 'pixel_7_7']


In [ ]:
df=pd.DataFrame(digit_data.data, columns=digit_data.feature_names)
df["target"]=pd.Series(digit_data.target)

In [ ]:
df.head()

pixel_0_0  pixel_0_1  pixel_0_2  pixel_0_3  pixel_0_4  pixel_0_5  \
0        0.0        0.0        5.0       13.0        9.0        1.0   
1        0.0        0.0        0.0       12.0       13.0        5.0   
2        0.0        0.0        0.0        4.0       15.0       12.0   
3        0.0        0.0        7.0       15.0       13.0        1.0   
4        0.0        0.0        0.0        1.0       11.0        0.0   

   pixel_0_6  pixel_0_7  pixel_1_0  pixel_1_1  ...  pixel_6_7  pixel_7_0  \
0        0.0        0.0        0.0        0.0  ...        0.0        0.0   
1        0.0        0.0        0.0        0.0  ...        0.0        0.0   
2        0.0        0.0        0.0        0.0  ...        0.0        0.0   
3        0.0        0.0        0.0        8.0  ...        0.0        0.0   
4        0.0        0.0        0.0        0.0  ...        0.0        0.0   

   pixel_7_1  pixel_7_2  pixel_7_3  pixel_7_4  pixel_7_5  pixel_7_6  \
0        0.0        6.0       13.0       10.0        0.0        0.0   
1        0.0        0.0       11.0       16.0       10.0        0.0   
2        0.0        0.0        3.0       11.0       16.0        9.0   
3        0.0        7.0       13.0       13.0        9.0        0.0   
4        0.0        0.0        2.0       16.0        4.0        0.0   

   pixel_7_7  target  
0        0.0       0  
1        0.0       1  
2        0.0       2  
3        0.0       3  
4        0.0       4  

[5 rows x 65 columns]

In [ ]:
from sklearn.model_selection import train_test_split
data_train, data_test, target_train, target_test = train_test_split(digit_data.data,
digit_data.target, test_size = 0.35, random_state = 51)
print(data_test)
data_train

[[ 0.  0.  3. ...  0.  0.  0.]
 [ 0.  0.  3. ...  0.  0.  0.]
 [ 0.  0.  1. ...  0.  0.  0.]
 ...
 [ 0.  0.  9. ...  1.  0.  0.]
 [ 0.  0.  9. ... 16.  6.  0.]
 [ 0.  1. 14. ...  4.  0.  0.]]


array([[ 0.,  1.,  9., ...,  0.,  0.,  0.],
       [ 0.,  0., 11., ...,  0.,  0.,  0.],
       [ 0.,  5., 16., ...,  1.,  0.,  0.],
       ...,
       [ 0.,  0.,  0., ..., 15.,  2.,  0.],
       [ 0.,  0.,  0., ..., 13.,  3.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [ ]:
import numpy as np
gnb = GaussianNB()
gnb.fit(data_train, target_train)
target_pred = gnb.predict(data_test)

In [ ]:
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(target_test, target_pred))

Accuracy: 0.8457869634340223


In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(target_test, target_pred)

array([[64,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 55,  0,  0,  0,  0,  2,  1,  4,  3],
       [ 0,  4, 32,  0,  0,  0,  1,  0, 14,  0],
       [ 0,  1,  1, 49,  0,  1,  1,  3,  5,  3],
       [ 0,  4,  0,  0, 55,  0,  2,  5,  2,  0],
       [ 0,  1,  0,  0,  0, 61,  1,  3,  2,  0],
       [ 0,  1,  0,  0,  0,  1, 64,  0,  0,  0],
       [ 0,  0,  0,  0,  1,  0,  0, 54,  0,  0],
       [ 0,  7,  0,  0,  0,  1,  0,  2, 51,  0],
       [ 0,  2,  2,  3,  2,  1,  0,  6,  4, 47]])

In [ ]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
precision = precision_score(target_test, target_pred, average=None)
recall = recall_score(target_test, target_pred, average=None)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

precision: [1.         0.73333333 0.91428571 0.94230769 0.94827586 0.93846154
 0.90140845 0.72972973 0.62195122 0.88679245]
recall: [1.         0.84615385 0.62745098 0.765625   0.80882353 0.89705882
 0.96969697 0.98181818 0.83606557 0.70149254]
